print('******welcome to python******')
print('*********************************')
print('please enter your name:')
myname=input()
print('hi Mr/Ms'+ myname + 'welcome to python')
print('please enter your age:')
myage=input()
print('your age will be'+str(int(myage)+1)+'in a year')
print('the length of your name:')
print(len(myname))
